### ISSUE TITLE
please, add support for vs2019

### ISSUE THREAD

**Issue by aiprog** [poma/MinimalisticView#9]
thank you very much

**Comment by TJHeuvel** [comment]
Came to ask for this!

**Comment by poma** [comment]
Added VS 2019 support but still working on AsyncPackage in [async-package](https://github.com/poma/MinimalisticView/tree/async-package) branch, I've done all the required changes but have a compile error:

```
CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, Boolean register, RegistrationMode mode)
   at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments)
   at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments)
Could not load type 'Microsoft.VisualStudio.Shell.IAsyncServiceProvider2' from assembly 'Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Trying to solve it at the moment. Also will try to integrate feedback button hiding.

**Comment by poma** [comment]
Done, also migrated to AsyncPackage. Also added an option to remove feedback button. In the process found a new but in VS 2019 - #11

**Comment by TJHeuvel** [comment]
I cant use my toolbars because the title opens. https://gfycat.com/FlashySorrowfulBoa
